# Generated by Django 5.0.6 on 2024-07-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0002_authors_remove_book_authors_bookauthors_book_authors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(
                related_name="book", through="book.BookAuthors", to="book.authors"
            ),
        ),
    ]
