# Generated by Django 5.0.6 on 2024-07-04 10:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0003_alter_book_authors"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Authors",
            new_name="Author",
        ),
        migrations.RenameModel(
            old_name="BookAuthors",
            new_name="BookAuthor",
        ),
    ]
